apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-order-api
  namespace: grupo-4-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-order-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-order-api
    spec:
      containers:
        - name: rvsfrebeca-order-api
          image: rvsfrebeca/imagem-orders-api
          ports:
            - containerPort: 8082
          env:
            - name: DB_ORDERS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-key-secret-credentials
                  key: DB_ORDER_USERNAME
            - name: DB_ORDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-key-secret-credentials
                  key: DB_ORDERS_PASSWORD
            - name: DB_ORDERS_URL
              valueFrom:
                secretKeyRef:
                    name: db-key-secret-credentials
                    key: DB_ORDERS_URL
            - name: SECRET_KEY_TOKEN
              valueFrom:
                secretKeyRef:
                    name: db-key-secret-credentials
                    key: SECRET_KEY_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-order
  namespace: grupo-4-namespace
spec:
  type: ClusterIP
  selector:
    app: deployment-order-api
  ports:
    - port: 8082
      targetPort: 8082