apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user-api
  namespace: grupo-4-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-user-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-user-api
    spec:
      containers:
        - name: rvsfrebeca-users-api
          image: rvsfrebeca/imagem-users-api
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-key-secret-credentials
                  key: DB_USERS_USERNAME
            - name: DB_USERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-key-secret-credentials
                  key: DB_USERS_PASSWORD
            - name: DB_USERS_URL
              valueFrom:
                secretKeyRef:
                    name: db-key-secret-credentials
                    key: DB_USERS_URL
            - name: SECRET_KEY_TOKEN
              valueFrom:
                secretKeyRef:
                    name: db-key-secret-credentials
                    key: SECRET_KEY_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-user
  namespace: grupo-4-namespace
spec:
  type: ClusterIP
  selector:
    app: deployment-user-api
  ports:
    - port: 8081
      targetPort: 8081